// Add any additional repositories for your dependencies here.

repositories {
    maven {
        name = "ModMaven"
        url = uri("https://modmaven.dev/")
        metadataSources {
            mavenPom()
            artifact()
        }
    }

    maven {
        name = "JitPack"
        url = uri("https://jitpack.io")
    }

    maven {
        name = "CurseMaven"
        url = uri("https://cursemaven.com")
        content {
            includeGroup("curse.maven")
        }
    }

}
